[package]
name = "indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.28"
postgres = "0.19.12"
serde = { version="1.0.228", features=["derive"]}
serde_yaml = "0.9.34"
url = "2.5.7"
